import Ps6_6: ((_#6 *a *b *c *d *e *f)->*f) {# ARITY _ = 1 #}{# STRICTNESS _ = "0,F" ST #};
import Ps6_5: ((_#6 *a *b *c *d *e *f)->*e) {# ARITY _ = 1 #}{# STRICTNESS _ = "0,F" ST #};
import Ps6_4: ((_#6 *a *b *c *d *e *f)->*d) {# ARITY _ = 1 #}{# STRICTNESS _ = "0,F" ST #};
import Ps6_3: ((_#6 *a *b *c *d *e *f)->*c) {# ARITY _ = 1 #}{# STRICTNESS _ = "0,F" ST #};
import Ps6_2: ((_#6 *a *b *c *d *e *f)->*b) {# ARITY _ = 1 #}{# STRICTNESS _ = "0,F" ST #};
import Ps6_1: ((_#6 *a *b *c *d *e *f)->*a) {# ARITY _ = 1 #}{# STRICTNESS _ = "0,F" ST #};
import Ps5_5: ((_#5 *a *b *c *d *e)->*e) {# ARITY _ = 1 #}{# STRICTNESS _ = "0,F" ST #};
import Ps5_4: ((_#5 *a *b *c *d *e)->*d) {# ARITY _ = 1 #}{# STRICTNESS _ = "0,F" ST #};
import Ps5_3: ((_#5 *a *b *c *d *e)->*c) {# ARITY _ = 1 #}{# STRICTNESS _ = "0,F" ST #};
import Ps5_2: ((_#5 *a *b *c *d *e)->*b) {# ARITY _ = 1 #}{# STRICTNESS _ = "0,F" ST #};
import Ps5_1: ((_#5 *a *b *c *d *e)->*a) {# ARITY _ = 1 #}{# STRICTNESS _ = "0,F" ST #};
import Ps4_4: ((_#4 *a *b *c *d)->*d) {# ARITY _ = 1 #}{# STRICTNESS _ = "0,F" ST #};
import Ps4_3: ((_#4 *a *b *c *d)->*c) {# ARITY _ = 1 #}{# STRICTNESS _ = "0,F" ST #};
import Ps4_2: ((_#4 *a *b *c *d)->*b) {# ARITY _ = 1 #}{# STRICTNESS _ = "0,F" ST #};
import Ps4_1: ((_#4 *a *b *c *d)->*a) {# ARITY _ = 1 #}{# STRICTNESS _ = "0,F" ST #};
import Ps3_3: ((_#3 *a *b *c)->*c) {# ARITY _ = 1 #}{# STRICTNESS _ = "0,F" ST #};
import Ps3_2: ((_#3 *a *b *c)->*b) {# ARITY _ = 1 #}{# STRICTNESS _ = "0,F" ST #};
import Ps3_1: ((_#3 *a *b *c)->*a) {# ARITY _ = 1 #}{# STRICTNESS _ = "0,F" ST #};
import Ps2_2: ((*a # *b)->*b) {# ARITY _ = 1 #}{# STRICTNESS _ = "0,F" ST #};
import Ps2_1: ((*a # *b)->*a) {# ARITY _ = 1 #}{# STRICTNESS _ = "0,F" ST #};
