nonfix  "show_#8";
nonfix  "show_#7";
nonfix  "show_#6";
nonfix  "show_#5";
nonfix  "show_#4";
nonfix  "show_#3";
nonfix  "show_#2";
import printString: (String->(*a->(List Request))) {# ARITY _ = 2 #}{# STRICTNESS _ = "T,T" ST #};
import show_String: ((List Char)->(List Char)) {# ARITY _ = 1 #}{# STRICTNESS _ = "T,F" ST #};
import show_Integer: (Integer->(List Char)) {# ARITY _ = 1 #}{# STRICTNESS _ = "0,F" ST #};
import show_Double: (Double->(List Char)) {# ARITY _ = 1 #}{# STRICTNESS _ = "0,0" ST #};
import show_OK: ((*a->(List Char))->((*b->(List Char))->((OK *a *b)->(List Char)))) {# ARITY _ = 3 #}{# STRICTNESS _ = "2,F" ST #};
import show_LArray: ((*a->(List Char))->((LArray *a)->(List Char))) {# ARITY _ = 2 #}{# STRICTNESS _ = "T,F" ST #};
import (show_#8): ((*a->(List Char))->((*b->(List Char))->((*c->(List Char))->((*d->(List Char))->((*e->(List Char))->((*f->(List Char))->((*g->(List Char))->((*h->(List Char))->((#8 *a *b *c *d *e *f *g *h)->(List Char)))))))))) {# ARITY _ = 9 #}{# STRICTNESS _ = "8,F" ST #};
import (show_#7): ((*a->(List Char))->((*b->(List Char))->((*c->(List Char))->((*d->(List Char))->((*e->(List Char))->((*f->(List Char))->((*g->(List Char))->((#7 *a *b *c *d *e *f *g)->(List Char))))))))) {# ARITY _ = 8 #}{# STRICTNESS _ = "7,F" ST #};
import (show_#6): ((*a->(List Char))->((*b->(List Char))->((*c->(List Char))->((*d->(List Char))->((*e->(List Char))->((*f->(List Char))->((#6 *a *b *c *d *e *f)->(List Char)))))))) {# ARITY _ = 7 #}{# STRICTNESS _ = "6,F" ST #};
import (show_#5): ((*a->(List Char))->((*b->(List Char))->((*c->(List Char))->((*d->(List Char))->((*e->(List Char))->((#5 *a *b *c *d *e)->(List Char))))))) {# ARITY _ = 6 #}{# STRICTNESS _ = "5,F" ST #};
import (show_#4): ((*a->(List Char))->((*b->(List Char))->((*c->(List Char))->((*d->(List Char))->((#4 *a *b *c *d)->(List Char)))))) {# ARITY _ = 5 #}{# STRICTNESS _ = "4,F" ST #};
import (show_#3): ((*a->(List Char))->((*b->(List Char))->((*c->(List Char))->((#3 *a *b *c)->(List Char))))) {# ARITY _ = 4 #}{# STRICTNESS _ = "3,F" ST #};
import (show_#2): ((*a->(List Char))->((*b->(List Char))->((*a # *b)->(List Char)))) {# ARITY _ = 3 #}{# STRICTNESS _ = "2,F" ST #};
import show_Char: (Char->(List Char)) {# ARITY _ = 1 #}{# STRICTNESS _ = "0,0" ST #};
import show_Bool: (Bool->String) {# ARITY _ = 1 #}{# STRICTNESS _ = "0,0" ST #};
import show_Int: (Int->(List Char)) {# ARITY _ = 1 #}{# STRICTNESS _ = "0,F" ST #};
import show_List: ((*a->(List Char))->((List *a)->(List Char))) {# ARITY _ = 2 #}{# STRICTNESS _ = "T,F" ST #};
