#ifndef _tagtable_h
#define _tagtable_h

#define O_STRING_F   4
#define O_STRINGN_F  5
#define O_INPUTD_F   6
#define O_INPUT_F    7
#define O_AP         8
#define O_APG        9
#define O_VAP       10
#define O_VAPG      11
#define O_ZAP       12
#define O_HOLE      13
#define O_STRING    14
#define O_STRINGN   15
#define O_INPUT     16
#define O_INPUTD    17
#define O_INDIR     18

#define O_CANON	    19	/* canonical nodes above this */

#define O_CAP       19
#define O_CAP_1     20 /* Only generated by gc */
#define O_CAP_2     21 /* Only generated by gc */
#define O_FUN       22

#define O_CANONDATA 23 /* constructor node above this */

#define O_INT       23
#define O_SFLOAT    24
#define O_DFLOAT    25
#define O_BIGNUM    26
#define O_CHAR      27
#define O_PAIR      28
#define O_PAIR0     29
#define O_PAIR1     30
#define O_PAIR2     31
#define O_PAIR3     32
#define O_PAIR4     33
#define O_TAG       34
#define O_TAG0      35
#define O_VEK       36
#define O_DVEK      37

#define O_MARKED    38
#define O_MOVED     39
#define O_GCRET     40
#define O_GSRET     41

#define NTAGS 84

/* values in each tag entry: */
/*#define	oeval	0*/
/*#define	ounwind 1*/
/*#define	ojfun	2*/
/*#define	ogettag	3*/
#define	ogc	 4
#define	ocmp 	 5
#define	oprint 	 6
#define oforce 	 7
/*#define o???     8*/
#define ogenc    9
#define ogens   10
#define omajorc 11
#define ogcsamp	12
#if 1
#define ogen2dt	13
#define extra2	14
#define extra3	15
#else
#define oBmove	13
#define oBscan	14
#define oBscanO	15
#endif
#define oJmove	16
#define ogen2s  17
#define ogen2c  18
#define ogen2t  19
#define ogen2p  20
#define oconstr 21
#define ogen2l  22
#define ogen2m  23
#define ogen2d  24

#define TAGTABLESIZE 25

#endif
