HOBJ = \
	C_Eq.o C_Ord.o C_Num.o C_Real.o C_Integral.o C_Fractional.o \
	C_Floating.o C_RealFrac.o C_RealFloat.o C_Enum.o \
	C_Bounded.o C_Show.o C_Read.o C_Data.o \
	C_Functor.o C_Monad.o C_Monad0.o C_MonadPlus.o \
	\
	Ratio.o Ratio__approxRational.o \
	I_Data.o I_Void.o \
	I_Unit.o I_Maybe.o I_Either.o I_Ordering.o I_List.o \
	I_P2.o I_Ix_P2.o I_P3.o I_P4.o I_P5.o \
	I_Bnd_Bool.o I_Bnd_Char.o I_Bnd_Int.o I_Bnd_Ordering.o \
	I_Eq_Bool.o I_Eq_Char.o I_Eq_Int.o I_Eq_Integer.o I_Eq_Float.o I_Eq_Double.o \
	I_Ord_Bool.o I_Ord_Char.o I_Ord_Int.o I_Ord_Integer.o I_Ord_Float.o I_Ord_Double.o \
	I_Num_Int.o I_Num_Integer.o I_Num_Float.o I_Num_Double.o \
	I_Real_Int.o I_R_Integer.o I_Real_Float.o I_Real_Double.o \
	I_Enum_Int.o I_E_Integer.o I_Enum_Float.o I_Enum_Double.o I_Enum_Bool.o I_Enum_Char.o \
	I_I_Int.o I_I_Integer.o \
	I_Fr_Float.o I_Fr_Double.o \
	I_RFr_Float.o I_RFr_Double.o \
	I_RFl_Float.o I_RFl_Double.o \
	I_Fl_Float.o I_Fl_Double.o \
	IR_Bool.o IR_Char.o IR_Int.o IR_Integer.o IR_List.o IR_P2.o IR_P3.o \
	IR_P4.o IR_P5.o IR_Unit.o IR_numbers.o \
	IS_Bool.o IS_Char.o IS_Int.o IS_Integer.o IS_List.o IS_P2.o IS_P3.o \
	IS_P4.o IS_P5.o IS_Unit.o IS_function.o IS_numbers.o IS_IO.o \
	I_Monad.o \
	RF_Spec.o \
	_ByteVector.o _BV_Inst.o \
	\
	_LibDialogue.o \
	_LibIOErrno.o \
	_LibArray.o \
	_LibIO.o _LibIO_all.o _LibIO__mkErrMsg.o _LibIO__ioToDialogue.o _LibIO__process.o \
	_LibIO__fail.o _LibIO__dialogueToIO.o _LibIO___unsafePerformIO.o _LibIO__instance.o \
	IOError.o \
	MonadicIO.o \
	StdIO.o StdIO__std.o StdIO__data.o StdIO__openFile.o StdIO__hClose.o StdIO__hIsEOF.o \
	\
	Char__readLitChar.o Char__showLitChar.o \
	Random.o Char.o List.o \
	ReadTextIO.o WriteTextIO.o IO.o \
	Locale.o Time.o CPUTime.o \
	Directory.o System.o \
	Ix.o Complex.o \
	Monad.o Maybe.o \
	Array.o Array__array.o Array__bang.o \
	Numeric.o Numeric__formatRealFloat.o Numeric__fromRat.o \
	Numeric__readInt.o Numeric__readFloat.o Numeric__readSigned.o \
	Numeric__showFloat.o Numeric__showSigned.o Numeric__showInt.o \
	\
	PP_subtract.o PP_even.o PP_odd.o PP_gcd.o PP_lcm.o PP_nexp.o \
	PP_fexp.o PP_fIntegral.o PP_fRealFrac.o PP_atan2.o PP_succ.o PP_pred.o \
	PP_seq.o PP_strict.o PP_land.o PP_lor.o PP_not.o PP_otherwise.o \
	PP_either.o PP_fst.o PP_snd.o PP_curry.o PP_uncurry.o PP_id.o \
	PP_const.o PP_compose.o PP_flip.o PP_dollar.o PP_until.o \
	PP_asTypeOf.o PP_undefined.o PP_error.o PP_maybe.o \
        PP_accumulate.o PP_sequence.o PP_guard.o PP_mapM.o PP_mapM_.o PP_applyM.o \
	PL_head.o PL_last.o PL_tail.o PL_init.o PL_null.o \
	PL_length.o PL_sub.o PL_filter.o \
	PL_foldl.o PL_foldl1.o PL_scanl.o PL_scanl1.o \
	PL_foldr.o PL_foldr1.o PL_scanr.o PL_scanr1.o PL_iterate.o \
	PL_repeat.o PL_replicate.o PL_cycle.o PL_take.o PL_drop.o PL_splitAt.o \
	PL_takeWhile.o PL_dropWhile.o PL_span.o PL_break.o PL_lines.o \
	PL_words.o PL_unlines.o PL_unwords.o PL_reverse.o \
	PL_and.o PL_or.o PL_any.o PL_all.o \
	PL_elem.o PL_notElem.o PL_lookup.o PL_sum.o PL_product.o \
	PL_maximum.o PL_minimum.o PL_concat.o PL_concatMap.o \
	PL_zipWith.o PL_zipWith3.o PL_zip.o PL_zip3.o PL_unzip.o PL_unzip3.o \
	PT_reads.o PT_shows.o PT_read.o PT_show.o PT_showChar.o PT_showString.o \
	PT_showParen.o PT_readParen.o PT_showType.o PT_lex.o PT_readRec.o PIO.o \
	\
	never.o enum.o misc.o gencmp.o \
	_XI_Command.o _XI_Event.o _XI_ResourceIds.o _XI_Sockets.o _XI_Xtypes.o

EOBJ =	Main_main.o

LIBP = \
	IOError.p MonadicIO.p StdIO.p \
	ReadTextIO.p WriteTextIO.p IO.p \
	Directory.p System.p \
	Ratio.p Ix.p Array.p Complex.p \
	Monad.p List.p Char.p Maybe.p Numeric.p \
	Time.p CPUTime.p Random.p Locale.p
LIBFILES = \
	IOError MonadicIO StdIO \
	ReadTextIO WriteTextIO IO \
	Directory System \
	Ratio Ix Array Complex \
	Monad List Char Maybe Numeric \
	Time CPUTime Random Locale

OBJ = $(HOBJ) $(EOBJ)

PHI = PP_*.hi PL_*.hi PT_*.hi PIO.hi
IPHI = I_*.hi IS_*.hi IR_*.hi

LIB = hlib1.3
DST = /usr/local/lib/lmlc
LMLC = lmlc
HBC = hbc -H25M
ASM = sh ../bin/asm
MYAS = sh ../bin/myas
RANLIB = sh ../bin/myranlib
HBCPROF=
LMLPROF=
CPROF=
IFLAGS = -fno-zap-redex -fcaf-call
ZAP= -fpbu -O
XASMFLAGS = $(ASMFLAGS) $(ASMPROF)
HBCN = $(HBCPROF) -z -cpp -1.3 -no-pedantic -fno-monad-compr $(ZAP)
HBCF = $(HBCN) -fprelude
XHBCFLAGS = $(HBCF) $(HBCFLAGS)
XHBCFLAGSN = $(HBCN) -fallow-redef -fno-syn-expand $(HBCFLAGS)
XHBCFLAGSI = $(HBCF) -fno-toprec $(HBCFLAGS)
PARSEP = ../bin/curryp -z -p -3
CC = sh ../bin/mycc
XCFLAGS = -O $(CPROF) $(CFLAGS)
XLMLFLAGS = $(ZAP) $(LMLPROF) $(LMLFLAGS)
CPP = sh ../bin/mycpp -C
MKDIR = sh ../bin/cmkdir
BUILDSHLIB = sh ../bin/buildshlib
MKIPREL = sh ../bin/mkiprel
AR = ar
LIBS = lib*.a
SHLIBS = lib.so

.SUFFIXES:
.SUFFIXES:	.o .M .m .c .hs .has .p .hi

.M.o:
	$(ASM) $(XASMFLAGS) $*.M

.m.o:
	$(LMLC) $(XLMLFLAGS) -c -Z $*.m

.hs.o:
	$(HBC) $(XHBCFLAGS) -c $*.hs

.has.o:
	$(HBC) $(XHBCFLAGSI) -c $*.has

.c.o:
	$(CC) $(XCFLAGS) -c $*.c

.hi.p:
	$(CPP) $*.hi | $(PARSEP) > $*.p

#.o.hi:
#	@echo ''

noprof:	lib.a lib.so Prelude.p ${LIBP}

timeprof: lib_p.a

heapprof: lib_ph.a

lib.a: 	${OBJ} ${PREL}
	rm -f lib.a
	ar cr lib.a ${OBJ}
	$(RANLIB) lib.a

lib.so:	lib.a
	$(BUILDSHLIB) $(DST)/$(LIB) lib.so ${OBJ}


lib_p.a:	${OBJ}
	$(MKDIR) normo profo
	-mv -f *.o lib.a normo
	@touch profo/DUMMY.o
	mv -f profo/*.o .
	make HBCPROF=-p LMLPROF=-p ASMPROF=-DPROFILE CPROF=-p lib.a
	mv lib.a lib_p.a
	mv *.o profo
	-mv normo/* .

lib_ph.a:	${OBJ}
	$(MKDIR) normo hprofo
	-mv -f *.o lib.a lib.so normo
	@touch hprofo/DUMMY.o
	mv -f hprofo/*.o .
	make HBCPROF=-ph LMLPROF=-ph ASMPROF=-DHPROFILE CPROF=-DHPROFILE lib.a lib.so
	mv lib.a lib_ph.a
	-mv lib.so lib_ph.so
	mv *.o hprofo
	mv normo/* .

Hprel.o:	$(HOBJ)
	$(MKDIR) normo hprelo
	-mv -f *.o lib.a normo
	@touch hprelo/DUMMY.o
	mv -f hprelo/*.o .
	-make HBCPROF='$(IFLAGS)' LMLPROF='$(IFLAGS)' Hprelo
	mv *.o hprelo
	mv normo/* .
	-mv Hprelo Hprel.o

Hprelo:	$(HOBJ)
	$(MKIPREL) Hprelo $(HOBJ)
	$(BUILDSHLIB) $(DST)/$(LIB) lib_i.so $(HOBJ)

Prelude.hi:	Prelude.phi ${PHI} ${IPHI} phi.sed iphi.sed Ratio.hi
	-mv Prelude.hi Prelude.hi.old
	cp Prelude.phi Prelude.hi
	sed -f phi.sed ${PHI} >> Prelude.hi
	cat PIO.hi ${IPHI} | sed -f iphi.sed >> Prelude.hi
	sed -f iphi.sed Ratio.hi | grep 'Ratio a' | sed 's/Ratio/Ratio.Ratio/' >> Prelude.hi

gencmp.o:	gencmp.m
	$(LMLC) $(XLMLFLAGS) -c -t -fno-zap-redex -fno-eta-expand -fno-const-caf -Z gencmp.m


C_Integral.o:	Ix.o
_LibIO.o:	_LibIO.hs
	$(HBC) $(XHBCFLAGSN) -c _LibIO.hs
_LibIO_all.o:	_LibIO_all.hs _LibIO.o _LibIO__ioToDialogue.o _LibIO__process.o _LibIO__mkErrMsg.o _LibIO__fail.o _LibIO__dialogueToIO.o _LibIO___unsafePerformIO.o _LibIO__instance.o
	$(HBC) $(XHBCFLAGSN) -c _LibIO_all.hs
_LibIO__ioToDialogue.o:	_LibIO__ioToDialogue.hs _LibIO.o _LibIO__mkErrMsg.o
	$(HBC) $(XHBCFLAGSN) -c _LibIO__ioToDialogue.hs
_LibIO__process.o:	_LibIO__process.hs _LibIO.o _LibIO__fail.o
	$(HBC) $(XHBCFLAGSN) -c _LibIO__process.hs
_LibIO__mkErrMsg.o:	_LibIO__mkErrMsg.hs _LibIO.o
	$(HBC) $(XHBCFLAGSN) -c _LibIO__mkErrMsg.hs
_LibIO__fail.o:	_LibIO__fail.hs _LibIO.o
	$(HBC) $(XHBCFLAGSN) -c _LibIO__fail.hs
_LibIO__dialogueToIO.o:	_LibIO__dialogueToIO.hs _LibIO.o
	$(HBC) $(XHBCFLAGSN) -c _LibIO__dialogueToIO.hs
_LibIO___unsafePerformIO.o:	_LibIO___unsafePerformIO.hs _LibIO.o
	$(HBC) $(XHBCFLAGSN) -c _LibIO___unsafePerformIO.hs
_LibIO__instance.o:	_LibIO__instance.hs _LibIO.o
	$(HBC) $(XHBCFLAGSN) -c _LibIO__instance.hs
_LibIOErrno.o:	_LibIOErrno.hs  myerrno.h _LibIO.o
	$(HBC) $(XHBCFLAGSN) -c _LibIOErrno.hs
myerrno.h:	myerrno.c /usr/include/errno.h
	sh ../bin/mycc -E myerrno.c | grep '^e.*=.*::' > myerrno.h
_LibDialogue.o:	_LibDialogue.hs _XStuff.hi ../hlib/P_IO_data.hs
	$(HBC) $(XHBCFLAGSN) -c _LibDialogue.hs
Array.o:	Array.hs _LibArray.o Ix.o List.o Array__array.o Array__bang.o
	$(HBC) $(XHBCFLAGSN) -c Array.hs
Array__array.o:	Array__array.hs _LibArray.o Ix.o
	$(HBC) $(XHBCFLAGSN) -c Array__array.hs
Array__bang.o:	Array__array.hs _LibArray.o Ix.o
	$(HBC) $(XHBCFLAGSN) -c Array__bang.hs
Char.o:	Char.hs Char__readLitChar.o Char__showLitChar.o
	$(HBC) $(HBCPROF) $(ZAP) -no-pedantic -fno-syn-expand -c Char.hs
Char__readLitChar.o:	### Numeric__readInt.o Char.o
	$(HBC) $(XHBCFLAGSN) -c Char__readLitChar.hs
Char__showLitChar.o:	### Char.o
	$(HBC) $(XHBCFLAGSN) -c Char__showLitChar.hs
Random.o:	Random.hs
	$(HBC) $(XHBCFLAGSN) -c Random.hs
Complex.o:	Complex.hs
	$(HBC) $(XHBCFLAGSN) -c Complex.hs
CPUTime.o:	CPUTime.hs
	$(HBC) $(XHBCFLAGSN) -c CPUTime.hs
Directory.o:	Directory.hs IO.o _LibIO.o _LibDialogue.o Time.o
	$(HBC) $(XHBCFLAGSN) -c Directory.hs
IO.o:	IO.hs MonadicIO.o StdIO.o IOError.o ReadTextIO.o WriteTextIO.o
	$(HBC) $(XHBCFLAGSN) -c IO.hs
IOError.o:	IOError.hs _LibIO.o _LibDialogue.o _LibIOErrno.o
	$(HBC) $(XHBCFLAGSN) -c IOError.hs
Ix.o:	Ix.hs
	$(HBC) $(XHBCFLAGSN) -c Ix.hs
Locale.o:	Locale.hs
	$(HBC) $(XHBCFLAGSN) -c Locale.hs
MonadicIO.o:	MonadicIO.hs _LibIO.o _LibDialogue.o
	$(HBC) $(XHBCFLAGSN) -c MonadicIO.hs
Numeric.o:	Numeric.hs Numeric__fromRat.o Numeric__readFloat.o Numeric__readInt.o Numeric__readSigned.o Numeric__showFloat.o Numeric__formatRealFloat.o Numeric__showInt.o Numeric__showSigned.o
Numeric__fromRat.o:	Numeric__fromRat.hs Array.o
	$(HBC) $(XHBCFLAGSN) -c Numeric__fromRat.hs
Numeric__readFloat.o:	Numeric__readFloat.hs Char.o Ratio.o Numeric__readInt.o
	$(HBC) $(XHBCFLAGSN) -c Numeric__readFloat.hs
Numeric__readInt.o:	Numeric__readInt.hs Char.o
	$(HBC) $(XHBCFLAGSN) -c Numeric__readInt.hs
Numeric__readSigned.o:	Numeric__readSigned.hs
	$(HBC) $(XHBCFLAGSN) -c Numeric__readSigned.hs
Numeric__showInt.o:	Numeric__showInt.hs Char.o
	$(HBC) $(XHBCFLAGSN) -c Numeric__showInt.hs
Numeric__showSigned.o:	Numeric__showSigned.hs
	$(HBC) $(XHBCFLAGSN) -c Numeric__showSigned.hs
Numeric__showFloat.o:	Numeric__showFloat.hs Numeric__formatRealFloat.o
	$(HBC) $(XHBCFLAGSN) -c Numeric__showFloat.hs
Numeric__formatRealFloat.o:	Numeric__formatRealFloat.hs Array.o Char.o
	$(HBC) $(XHBCFLAGSN) -c Numeric__formatRealFloat.hs
Ratio.o:	Ratio.hs Ratio__approxRational.o
	$(HBC) $(XHBCFLAGSN) -c Ratio.hs
Ratio__approxRational.o:	Ratio__approxRational.hs
	$(HBC) $(XHBCFLAGSN) -c Ratio__approxRational.hs
ReadTextIO.o:	ReadTextIO.hs _LibIO.o _LibDialogue.o
	$(HBC) $(XHBCFLAGSN) -c ReadTextIO.hs
StdIO.o:	StdIO.hs MonadicIO.o _LibIO.o _LibDialogue.o StdIO__std.o StdIO__data.o StdIO__openFile.o StdIO__hClose.o StdIO__hIsEOF.o
	$(HBC) $(XHBCFLAGSN) -c StdIO.hs
StdIO__std.o:	StdIO__std.hs MonadicIO.o _LibIO.o _LibDialogue.o
	$(HBC) $(XHBCFLAGSN) -c StdIO__std.hs
StdIO__data.o:	StdIO__data.hs
	$(HBC) $(XHBCFLAGSN) -c StdIO__data.hs
StdIO__openFile.o:	StdIO__openFile.hs _LibIO.o _LibIO__process.o
	$(HBC) $(XHBCFLAGSN) -c StdIO__openFile.hs
StdIO__hClose.o:	StdIO__hClose.hs _LibIO.o _LibIO__process.o
	$(HBC) $(XHBCFLAGSN) -c StdIO__hClose.hs
StdIO__hIsEOF.o:	StdIO__hIsEOF.hs _LibIO.o _LibIO__process.o
	$(HBC) $(XHBCFLAGSN) -c StdIO__hIsEOF.hs
System.o:	System.hs IO.o _LibIO.o _LibDialogue.o
	$(HBC) $(XHBCFLAGSN) -c System.hs
WriteTextIO.o:	WriteTextIO.hs _LibIO.o _LibDialogue.o StdIO.o
	$(HBC) $(XHBCFLAGSN) -c WriteTextIO.hs
Monad.o:	Monad.hs
	$(HBC) $(XHBCFLAGSN) -c Monad.hs
Maybe.o:	Maybe.hs
	$(HBC) $(XHBCFLAGSN) -c Maybe.hs
List.o:	List.hs
	$(HBC) $(XHBCFLAGSN) -c List.hs
Time.o:	_LibDialogue.o _LibIO__process.o Array.o Char.o Locale.o Time.hs
	$(HBC) $(XHBCFLAGSN) -c Time.hs
_LibArray.o:	_LibArray.hs
	$(HBC) $(XHBCFLAGSN) -c _LibArray.hs


I_Real_Int.o:	Ratio.o
I_I_Int.o:	Ix.o
IS_Char.o:	Char__showLitChar.o
IR_Char.o:	Char__readLitChar.o
IR_Int.o:	Numeric.o
S_numbers.o:	Numeric.o
I_Fr_Double.o:	Numeric__fromRat.o
I_Fr_Float.o:	Numeric__fromRat.o

install:
	$(MKDIR) $(DST)/$(LIB)
	cp $(LIBS) $(DST)/$(LIB)
	sh ../bin/ccp $(SHLIBS) $(DST)/$(LIB)
	$(RANLIB) $(DST)/$(LIB)/lib*.a
	cp Prelude.p Prelude.hi UnicodeInfo $(DST)/$(LIB)
	sh -c 'for f in $(LIBFILES) ; do cp $$f.hi $$f.p $$f.o $(DST)/$(LIB) ; done'

install_Hprel:
	$(MKDIR) $(DST)/$(LIB)
	cp Hprel.o ihelp $(DST)/$(LIB)
	sh ../bin/ccp lib_i.so $(DST)/$(LIB)

clean:
	-rm -f *.o *.a *.so
	-rm -f saveo*/*
	-rm -f normo/*
	-rm -f profo/* 
	-rm -f hprofo/* 
	-rm -f hprelo/* 

oosave:
	mv *.o lib.a saveoo
	mv saveoo/runtime* .
unosave:
	mv saveoo/* .
osave:
	mv *.o lib.a saveo
	mv saveo/runtime* .
unsave:
	mv saveo/* .
