.TH LMLI 1 local
.SH NAME
lmli \- an interactive LML (Lazy ML)
.SH SYNOPSIS
.B lmli
.SH DESCRIPTION
.I Lmli
has very few commands.  You can load files, define and evaluate values.
See the LML manual for details.
.PP
The syntax of
.I LML
programs is described elsewhere.
.SH ENVIRONMENT
The environment variable LMLDIR is used to find the place to look for the
various files used by the compiler.  The default value is /usr/local/lib/lmlc.
.SH FILES
.TP 25
.B $LMLDIR/bin/lmlp
the parser program.
.TP
.B $LMLDIR/bin/lmlcomp
the interactive system proper.
.TP
.B $LMLDIR/lib/include/*
some type include files.
.TP
.SH DIAGNOSTICS
Bad for syntax errors.
Even worse for other errors.
.SH "SEE ALSO"
lmlc(1), lmlmake(1)
.SH BUGS
Definitely, yes!
