#define Ftmp4 (reg 54)
#define Ftmp1 (reg 56)
#define Ftmp2 (reg 58)
#define Ftmp3 (reg 60)
#define ROFFS 0
#define dtmp1 (reg (23-ROFFS))
#define dtmp2 (reg (24-ROFFS))
#define dtmp3 (reg (25-ROFFS))
#define dtmp4 (reg (18-ROFFS))
#define Addr (17-ROFFS)
#define Canon (19-ROFFS)
#define Spr (20-ROFFS)
#define hpr (21-ROFFS)
#define Ehpr (22-ROFFS)
#define Ret (26-ROFFS)
#define Proc (27-ROFFS)
#define At (28-ROFFS)
#define Gp (29-ROFFS)
#define Vpr (30-ROFFS)
#define Zero (31-ROFFS)

#define WSIZE 8
